/**
 * Test ID Builder Module
 * 
 * This module provides type-safe test ID generation utilities for use with
 * playwright-elements. It enables:
 * - Branded types for test IDs to prevent misuse
 * - Factory functions for generating IDs with consistent prefixes
 * - Static ID generation for simple cases
 * - React integration via testIdProps helper
 * 
 * @packageDocumentation
 */

/**
 * Unique brand symbol for TestId type
 */
declare const __testIdBrand: unique symbol;

/**
 * Branded string type for `data-testid` values.
 * The `Kind` parameter allows the type system to distinguish between different
 * categories of test IDs (e.g., a button ID vs. a container ID), preventing
 * them from being used interchangeably even though both are strings.
 * 
 * @example
 * ```typescript
 * type ButtonId = TestId<'button'>;
 * type ContainerId = TestId<'container'>;
 * 
 * const buttonId: ButtonId = sid('submit-button');
 * const containerId: ContainerId = sid('main-container');
 * 
 * // This would be a type error:
 * // const wrong: ButtonId = containerId; // Error: Type 'ContainerId' is not assignable to type 'ButtonId'
 * ```
 */
export type TestId<Kind extends string = string> = string & {
  readonly [__testIdBrand]: Kind;
};

/**
 * Joins array parts into a kebab-case string, filtering out null/undefined/empty values.
 * @param parts - Array of string or number parts to join
 * @returns Joined kebab-case string
 */
const join = (parts: ReadonlyArray<string | number | null | undefined>): string =>
  parts.filter((p) => p !== '' && p != null).join('-');

/**
 * Builds a static ID (no dynamic key) from one or more kebab-case parts.
 * Use this for test IDs that don't need parameterization.
 * 
 * @example
 * ```typescript
 * // Simple static ID
 * const submitButton = sid('submit-button');
 * 
 * // ID with multiple parts
 * const userProfileLink = sid('user', 'profile', 'link');
 * // Results in: 'user-profile-link'
 * 
 * // Typed static ID
 * const headerTitle: TestId<'header'> = sid('header-title');
 * ```
 * 
 * @param parts - String or number parts to join into the ID
 * @returns A TestId with the joined parts
 */
export const sid = <K extends string = string>(...parts: Array<string | number>): TestId<K> =>
  join(parts) as TestId<K>;

/**
 * A factory function for generating test IDs with a consistent prefix.
 * Each factory exposes its `.prefix` property so that tests can create
 * prefix-based selectors without duplicating the prefix string.
 * 
 * @example
 * ```typescript
 * // Create a factory for button IDs
 * const button = factory('btn');
 * 
 * // Generate specific IDs
 * button('submit');      // Returns: 'btn-submit' as TestId<'button'>
 * button('cancel');      // Returns: 'btn-cancel' as TestId<'button'>
 * 
 * // Access the prefix for prefix selectors
 * button.prefix;         // Returns: 'btn'
 * 
 * // Create typed factory
 * const ruleAction = factory<'rules.rowAction'>('rule-action');
 * ruleAction('edit');   // Returns: 'rule-action-edit' as TestId<'rules.rowAction'>
 * ```
 */
export interface IdFactory<K extends string = string> {
  (key: string | number): TestId<K>;
  /**
   * Static portion of the ID, with NO trailing `-`. 
   * Use for `[data-testid^=...]` prefix selectors.
   */
  readonly prefix: string;
  /**
   * Optional list of OTHER factory prefixes that intentionally share this prefix.
   * Used by consistency checks to allow declared collisions.
   * 
   * @example
   * ```typescript
   * // Both factories produce IDs starting with 'nudge-button'
   * const rowNudge = factory('nudge-button', {
   *   aliasPrefixes: ['nudge-button']
   * });
   * const categoryNudge = factory('nudge-button', {
   *   aliasPrefixes: ['nudge-button']
   * });
   * ```
   */
  readonly aliasPrefixes?: ReadonlyArray<string>;
}

/**
 * Creates an ID factory with a specified prefix.
 * 
 * @param prefix - The prefix to use for all IDs generated by this factory
 * @param opts - Optional configuration including alias prefixes
 * @returns An IdFactory configured with the given prefix
 */
export const factory = <K extends string = string>(
  prefix: string,
  opts?: { aliasPrefixes?: ReadonlyArray<string> },
): IdFactory<K> =>
  Object.assign(
    (key: string | number) => join([prefix, key]) as TestId<K>,
    {
      prefix,
      aliasPrefixes: opts?.aliasPrefixes,
    } as const
  );

/**
 * Creates a factory whose ENTIRE id is the key (no prefix).
 * Used for raw entity-id testids, such as when an ID is based on a database ID
 * or other unique identifier.
 * 
 * @example
 * ```typescript
 * // For components that use entity IDs directly
 * const ruleRow = bareFactory<'rules.row'>();
 * 
 * // Usage in component
 * <div {...testIdProps(ruleRow(ruleId))} />
 * // Results in: data-testid="123" (if ruleId is 123)
 * ```
 * 
 * @returns An IdFactory with an empty prefix
 */
export const bareFactory = <K extends string = string>(): IdFactory<K> =>
  Object.assign(
    (key: string | number) => String(key) as TestId<K>,
    {
      prefix: '',
    } as const
  );

/**
 * Returns props to spread onto a React/JSX element to attach the `data-testid` attribute.
 * 
 * @example
 * ```typescript
 * function MyComponent() {
 *   return <button {...testIdProps(sid('my-button'))}>Click me</button>;
 * }
 * 
 * // Or with a factory:
 * function RuleRow({ ruleId }: { ruleId: string }) {
 *   return <div {...testIdProps(ruleRow(ruleId))}>...</div>;
 * }
 * ```
 * 
 * @param id - The test ID (TestId or string) to attach to the element
 * @returns Object with data-testid property
 */
export const testIdProps = (id: TestId | string): { 'data-testid': string } => ({
  'data-testid': id as string,
});

/**
 * Type guard to check if a value is an IdFactory.
 * Used by consistency checks to validate factory usage.
 * 
 * @param v - The value to check
 * @returns true if v is an IdFactory, false otherwise
 */
export const isIdFactory = (v: unknown): v is IdFactory =>
  typeof v === 'function' && typeof (v as { prefix?: unknown }).prefix === 'string';
